version: '3.8'

services:
  mongodb:
    env_file:
      - .env
    image: mongo:5.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - mongo-data:/data/db

  nodejs-frontend:
    env_file:
      - .env
    image: node:alpine
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "${FRONTEND_PORT}:3000"
    command: npm start

  python-backend:
    env_file:
      - .env
    build: ./backend
    working_dir: /app
    volumes:
      - ./backend:/app
    ports:
      - "${BACKEND_PORT}:5000"
    command: python app.py

volumes:
  mongo-data: